#开发环境
log:
  level: INFO
server:
  port: 9199
  servlet:
    context-path: /demo
logging:
  config: classpath:logback-spring.xml
lzy:
  elasticsearch:
    host: 127.0.0.1:9200 #多个结点中间用逗号分隔
spring:
  devtools:
    restart:
      enabled: true #设置开启热部署
      additional-paths: src/main/java #重启目录
      exclude: WEB-INF/**
    freemarker:
      cache: false #页面不加载缓存，修改即时生效