#开发环境
log:
  level: INFO
server:
  port: 8999
  servlet:
    context-path: /demo
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/demo?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: eslink
    type: com.alibaba.druid.pool.DruidDataSource
  redis:
    redisson:
      # fixme config的配置最好去对应的实体类看下有没有这个属性，和网上直接找的会有一些出入
      file: classpath:/redisson/SingleRedisson.yaml
mybatis-plus:
  #  classpath:/com/*/*/mapper/*Mapper.xml 放在resources目录下classpath:/mapper/**.xml
  mapper-locations: classpath:/mapper/**.xml
#  type-aliases-package: com.example.demo.domain
#  configuration:
#  开启这个的作用是可以让数据库中的id与pojo中的id对应
#  map-underscore-to-camel-case: true
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
logging:
  config: classpath:logback-spring.xml
tokenConfig:
  open: false
path:
  desktop: C:\Users\84428\Desktop\

#参数间的引用
com:
  example:
    name: lzy
    title: spring boot
    desc: ${com.example.name}正在努⼒写《${com.example.title}》
    #使用随机数
    #随机字符串
    value: ${random.value}
    #随机int
    number: ${random.int}
    #随机long
    bignumber: ${random.long}
    #10以内的随机数
    test1: ${random.int(10)}
    #10-20的随机数
    test2: ${random.int[10,20]}